[package]
name = "ev_compiler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.13.0"
regex = "1.6.0"
colour = "0.6.0"
rand = "0.8.5"